### PR TITLE
UI improvements: translation, buttons

### PR DESCRIPTION
**Pull request by Frigory33**
Hi,

Here are quite a few fixes and improvements for WP Editor’s interface:
* all texts are now translatable from the ‘wp-editor’ text domain;
* files can be saved with Ctrl-S;
* clicking on save, undo and redo buttons no longer scrolls to the top of the page;
* I also fixed the file permissions.

Thanks for reviewing and merging.

### CODE REVIEW

**Comment by Frigory33** [comment]
Hi,
My changes include a translation into French, but then I noticed the GlotPress translation platform on the WordPress website. But I can’t find where I can upload my translation file into it. Do you have an idea? Would you need me to remove my translation file from the branch?
Furthermore, my changes also include some improvements concerning the UI, mainly for translation.
Please merge or justify.

**Comment by benjaminprojas** [comment]
@Frigory33 I'm sorry its taken a while to look over this PR.  Looks pretty good over all, just need to go through it a little more thoroughly.  Thank you!

**Comment by Frigory33** [comment]
Thanks for reviewing!
Do you have a suggestion for providing my French translation too? I can’t find where I should upload my PO file on GlotPress. I’ll have to ask the WordPress team.

**Comment by LoDef** [comment]
Will this be merged with base and go live soon? 
This tiny feature would be an awesome improvement for me:
> files can be saved with Ctrl-S;

All the clicking makes me go nuts... :P

**Comment by benjaminprojas** [comment]
@LoDef I am hoping to get to this soon. This is a hobby for me more than anything else so it takes time to get back to this plugin. Thanks for your patience!

**Comment by benjaminprojas** [comment]
With WordPress 5.0(gutenberg) imminent and also changes in 4.9 for syntax highlighting in the plugin/theme editors. I am closing the doors on this project.

**Pull request closed without merging**
